#!/bin/bash
set -e

docker rm -f feedread &>/dev/null && echo 'Removed old container'
docker rmi kereal/feedread &>/dev/null && echo 'Removed old image'

# make image
docker build -t kereal/feedread .
docker rmi `docker images --filter label=stage=builder -q`


# run with local db if file exists
DBNAME=feedread.sqlite3
docker run -idt \
  `[[ -f $DBNAME ]] && echo "-v $(pwd)/$DBNAME:/app/$DBNAME"` \
  --name feedread -p 3008:80 kereal/feedread


# docker push kereal/feedread
